# Generated by Django 3.2.12 on 2023-01-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
